shfSecurity:
  index:
    security: false
  logoin:
    security: false
  logout:
    security: true

default:
  index:
    security: true
    credentials:
      - [admin, cajero]
  insert:
    security: true